name = "UWCS Theme"
description = "Theme for the new UWCS website"
license = "MIT"
homepage = "https://github.com/uwcs/new-site"
min_version = "0.17.0"
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "Owen Connors"
homepage = "https://github.com/ericthelemur"
